# Generated by Django 4.2.30 on 2026-06-16 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccines', '0001_initial'),
        ('appointments', '0002_appointment_reminded_at_appointment_reminded_by'),
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_type', models.CharField(blank=True, max_length=100, verbose_name='关联体检类型')),
                ('event_type', models.CharField(choices=[('fever', '发热'), ('rash', '皮疹'), ('crying', '异常哭闹'), ('appetite', '食欲变化'), ('sleep', '睡眠异常'), ('doctor_followup', '医生回访建议'), ('other', '其他健康事件')], max_length=30, verbose_name='事件类型')),
                ('severity', models.CharField(choices=[('mild', '轻微'), ('moderate', '中等'), ('severe', '严重')], max_length=10, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('observing', '观察中'), ('need_revisit', '需复诊'), ('relieved', '已缓解'), ('archived', '已归档')], default='observing', max_length=20, verbose_name='事件状态')),
                ('occurrence_time', models.DateTimeField(verbose_name='发生时间')),
                ('symptoms', models.TextField(verbose_name='症状描述')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体温(℃)')),
                ('treatment', models.TextField(blank=True, verbose_name='处理措施')),
                ('doctor_advice', models.TextField(blank=True, verbose_name='医生建议')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='建议复诊日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_events', to='appointments.appointment', verbose_name='关联预约')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='babies.baby', verbose_name='宝宝')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_events', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('followed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_health_events', to=settings.AUTH_USER_MODEL, verbose_name='跟进负责人')),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_events', to='vaccines.vaccine', verbose_name='关联疫苗')),
            ],
            options={
                'verbose_name': '健康事件',
                'verbose_name_plural': '健康事件',
                'ordering': ['-occurrence_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthEventUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(default='progress', max_length=50, verbose_name='更新类型')),
                ('content', models.TextField(verbose_name='更新内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_event_updates', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='health_events.healthevent', verbose_name='健康事件')),
            ],
            options={
                'verbose_name': '健康事件进展',
                'verbose_name_plural': '健康事件进展',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthEventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='查看时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='health_events.healthevent', verbose_name='健康事件')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_health_events', to=settings.AUTH_USER_MODEL, verbose_name='查看人')),
            ],
            options={
                'verbose_name': '健康事件查看记录',
                'verbose_name_plural': '健康事件查看记录',
                'unique_together': {('event', 'viewer')},
            },
        ),
    ]
