# Generated by Django 4.2.30 on 2026-06-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='体检项目名称')),
                ('applicable_age_months', models.IntegerField(verbose_name='适用月龄')),
                ('checkup_items', models.JSONField(blank=True, default=list, verbose_name='体检项目')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '体检项目',
                'verbose_name_plural': '体检项目',
                'ordering': ['applicable_age_months'],
            },
        ),
        migrations.CreateModel(
            name='CheckupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField(verbose_name='体检日期')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身高(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='头围(cm)')),
                ('doctor_advice', models.TextField(blank=True, verbose_name='医生建议')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='下次就诊日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_records', to='babies.baby', verbose_name='宝宝')),
                ('checkup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='checkups.checkup', verbose_name='体检项目')),
            ],
            options={
                'verbose_name': '体检记录',
                'verbose_name_plural': '体检记录',
                'ordering': ['-checkup_date'],
            },
        ),
    ]
