# Generated by Django 4.2.30 on 2026-06-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccines', '0001_initial'),
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('vaccine', '疫苗接种'), ('checkup', '体检')], max_length=10, verbose_name='预约类型')),
                ('checkup_type', models.CharField(blank=True, max_length=100, verbose_name='体检类型')),
                ('appointment_date', models.DateField(verbose_name='预约日期')),
                ('time_slot', models.CharField(choices=[('morning_1', '上午第一时段'), ('morning_2', '上午第二时段'), ('morning_3', '上午第三时段'), ('afternoon_1', '下午第一时段'), ('afternoon_2', '下午第二时段'), ('afternoon_3', '下午第三时段')], max_length=20, verbose_name='时间段')),
                ('hospital', models.CharField(max_length=255, verbose_name='预约医院')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], max_length=10, verbose_name='预约状态')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='babies.baby', verbose_name='宝宝')),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vaccines.vaccine', verbose_name='疫苗')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'ordering': ['-appointment_date', 'time_slot'],
            },
        ),
    ]
