# Generated by Django 4.2.30 on 2026-06-16 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提醒时间'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提醒人'),
        ),
    ]
