# Generated by Django 4.2.30 on 2026-06-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='宝宝姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='出生体重(kg)')),
                ('vaccination_history', models.JSONField(blank=True, default=dict, verbose_name='接种历史')),
                ('hospital_preference', models.CharField(blank=True, max_length=255, verbose_name='偏好医院')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='babies', to='accounts.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '宝宝',
                'verbose_name_plural': '宝宝',
                'ordering': ['-created_at'],
            },
        ),
    ]
