# Generated by Django 4.2.30 on 2026-06-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(max_length=100, verbose_name='反应类型')),
                ('severity', models.CharField(choices=[('mild', '轻微'), ('moderate', '中等'), ('severe', '严重')], max_length=10, verbose_name='严重程度')),
                ('occurrence_time', models.DateTimeField(verbose_name='发生时间')),
                ('symptoms', models.TextField(verbose_name='症状')),
                ('treatment', models.TextField(blank=True, verbose_name='处理措施')),
                ('doctor_advice', models.TextField(blank=True, verbose_name='医生建议')),
                ('next_visit_notes', models.TextField(blank=True, verbose_name='复诊注意事项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='appointments.appointment', verbose_name='预约')),
            ],
            options={
                'verbose_name': '不良反应',
                'verbose_name_plural': '不良反应',
                'ordering': ['-occurrence_time'],
            },
        ),
    ]
