# Generated by Django 4.2.30 on 2026-06-17 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preparation', '0001_initial'),
        ('appointments', '0002_appointment_reminded_at_appointment_reminded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_events', '0001_initial'),
        ('accounts', '0001_initial'),
        ('reactions', '0001_initial'),
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(default='#6C5CE7', max_length=20, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资料标签',
                'verbose_name_plural': '资料标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='资料标题')),
                ('archive_type', models.CharField(choices=[('vaccine_certificate', '接种凭证'), ('checkup_report', '体检报告'), ('lab_result', '化验单'), ('doctor_advice', '医生建议'), ('revisit_note', '复诊单'), ('photo', '照片材料'), ('preparation_doc', '到院准备材料'), ('reaction_record', '反应观察记录'), ('other', '其他资料')], max_length=30, verbose_name='资料类型')),
                ('source_type', models.CharField(choices=[('manual', '手动上传'), ('appointment', '预约关联'), ('health_event', '健康事件关联'), ('reaction', '反应观察关联'), ('preparation', '到院准备关联'), ('vaccination', '接种记录关联')], default='manual', max_length=20, verbose_name='来源类型')),
                ('event_date', models.DateField(verbose_name='事件发生日期')),
                ('description', models.TextField(blank=True, verbose_name='资料描述')),
                ('doctor_name', models.CharField(blank=True, max_length=100, verbose_name='医生姓名')),
                ('hospital', models.CharField(blank=True, max_length=255, verbose_name='医院名称')),
                ('file_url', models.URLField(blank=True, verbose_name='文件URL')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='缩略图URL')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('approved', '已归档'), ('needs_action', '待处理'), ('expired', '已过期'), ('archived_obsolete', '已作废')], default='draft', max_length=20, verbose_name='资料状态')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('view_permission', models.CharField(choices=[('family_admin', '仅管理员'), ('family_all', '全体家庭成员'), ('custom', '指定成员')], default='family_all', max_length=20, verbose_name='查看权限')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('allowed_viewers', models.ManyToManyField(blank=True, related_name='allowed_archives', to=settings.AUTH_USER_MODEL, verbose_name='允许查看的成员')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives', to='appointments.appointment', verbose_name='关联预约')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_archives', to='babies.baby', verbose_name='宝宝')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_archives', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives', to='accounts.family', verbose_name='所属家庭')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_archives', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('health_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives', to='health_events.healthevent', verbose_name='关联健康事件')),
                ('preparation_checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives', to='preparation.preparationchecklist', verbose_name='关联到院准备')),
                ('reaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_archives', to='reactions.reaction', verbose_name='关联反应观察')),
                ('tags', models.ManyToManyField(blank=True, related_name='archives', to='medical_archives.archivetag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '就诊资料归档',
                'verbose_name_plural': '就诊资料归档',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='旧状态')),
                ('new_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('change_reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='medical_archives.medicalarchive', verbose_name='资料归档')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
            ],
            options={
                'verbose_name': '资料状态变更日志',
                'verbose_name_plural': '资料状态变更日志',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='查看时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='medical_archives.medicalarchive', verbose_name='资料归档')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_archives', to=settings.AUTH_USER_MODEL, verbose_name='查看人')),
            ],
            options={
                'verbose_name': '资料查看记录',
                'verbose_name_plural': '资料查看记录',
                'unique_together': {('archive', 'viewer')},
            },
        ),
    ]
