# Generated by Django 4.2.30 on 2026-06-16 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('babies', '0001_initial'),
        ('appointments', '0002_appointment_reminded_at_appointment_reminded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '准备中'), ('completed', '已完成'), ('verified', '已核验')], default='not_started', max_length=15, verbose_name='准备状态')),
                ('completion_rate', models.FloatField(default=0, verbose_name='完成率')),
                ('risk_notes', models.JSONField(blank=True, default=list, verbose_name='风险提示')),
                ('report_generated', models.BooleanField(default=False, verbose_name='已生成报告')),
                ('report_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='报告生成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_checklist', to='appointments.appointment', verbose_name='预约')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_checklists', to='babies.baby', verbose_name='宝宝')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '到院准备清单',
                'verbose_name_plural': '到院准备清单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('document', '证件材料'), ('vaccine_book', '疫苗本'), ('medical_history', '既往病史'), ('fasting', '空腹要求'), ('companion', '陪同人信息'), ('transport', '交通出发时间'), ('other', '其他')], max_length=20, verbose_name='分类')),
                ('item_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('item_description', models.TextField(blank=True, verbose_name='项目说明')),
                ('is_required', models.BooleanField(default=True, verbose_name='必选项')),
                ('confirmed', models.BooleanField(default=False, verbose_name='已确认')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='preparation.preparationchecklist', verbose_name='准备清单')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_items', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
            ],
            options={
                'verbose_name': '清单项',
                'verbose_name_plural': '清单项',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='核验时间')),
                ('carried_items', models.JSONField(blank=True, default=list, verbose_name='已携带材料')),
                ('missing_items', models.JSONField(blank=True, default=list, verbose_name='临时缺失项')),
                ('supplemented_items', models.JSONField(blank=True, default=list, verbose_name='现场补录项')),
                ('supplement_notes', models.TextField(blank=True, verbose_name='补录说明')),
                ('on_site_notes', models.TextField(blank=True, verbose_name='现场备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('checklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_verification', to='preparation.preparationchecklist', verbose_name='准备清单')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='核验人')),
            ],
            options={
                'verbose_name': '到院核验记录',
                'verbose_name_plural': '到院核验记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
