# Generated by Django 4.2.30 on 2026-06-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='疫苗名称')),
                ('short_name', models.CharField(max_length=50, verbose_name='疫苗简称')),
                ('vaccine_type', models.CharField(choices=[('free', '免费'), ('paid', '自费')], max_length=10, verbose_name='疫苗类型')),
                ('applicable_age_months', models.IntegerField(verbose_name='适用月龄')),
                ('dose_number', models.IntegerField(default=1, verbose_name='剂次')),
                ('route', models.CharField(choices=[('injection', '注射'), ('oral', '口服'), ('spray', '喷雾')], max_length=10, verbose_name='接种途径')),
                ('precautions', models.TextField(blank=True, verbose_name='注意事项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '疫苗',
                'verbose_name_plural': '疫苗',
                'ordering': ['applicable_age_months', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='计划接种日期')),
                ('status', models.CharField(choices=[('pending', '待接种'), ('completed', '已接种'), ('delayed', '已推迟')], max_length=10, verbose_name='接种状态')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际接种日期')),
                ('vaccination_site', models.CharField(blank=True, max_length=255, verbose_name='接种地点')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='babies.baby', verbose_name='宝宝')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='vaccines.vaccine', verbose_name='疫苗')),
            ],
            options={
                'verbose_name': '接种计划',
                'verbose_name_plural': '接种计划',
                'ordering': ['planned_date'],
            },
        ),
    ]
